name: flutter_sub
description: Idiomatic State Lifecycles for Flutter. Part of the State, part of the Tree.
repository: https://github.com/clragon/flutter_sub/

version: 3.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
